// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrntv9jlPFvh9v5gujtBJVXG5BdgdtdRY',
    appId: '1:372270835442:web:dc83a7d70ad655deed526b',
    messagingSenderId: '372270835442',
    projectId: 'mock-exam-maker-using-ai-9d0f5',
    authDomain: 'mock-exam-maker-using-ai-9d0f5.firebaseapp.com',
    storageBucket: 'mock-exam-maker-using-ai-9d0f5.appspot.com',
    measurementId: 'G-LX757ECED6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1OA6qRP2S6VCreSrmy5NMdHwoSWwElE',
    appId: '1:372270835442:android:a4c68de0254128cded526b',
    messagingSenderId: '372270835442',
    projectId: 'mock-exam-maker-using-ai-9d0f5',
    storageBucket: 'mock-exam-maker-using-ai-9d0f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaANAI_7Qz20NjYxrr2EpGzV1ObahgcE',
    appId: '1:372270835442:ios:173b1801ec0098bced526b',
    messagingSenderId: '372270835442',
    projectId: 'mock-exam-maker-using-ai-9d0f5',
    storageBucket: 'mock-exam-maker-using-ai-9d0f5.appspot.com',
    iosClientId: '372270835442-9sq10seokge0bs2bmn2641ubb8pifvn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaANAI_7Qz20NjYxrr2EpGzV1ObahgcE',
    appId: '1:372270835442:ios:173b1801ec0098bced526b',
    messagingSenderId: '372270835442',
    projectId: 'mock-exam-maker-using-ai-9d0f5',
    storageBucket: 'mock-exam-maker-using-ai-9d0f5.appspot.com',
    iosClientId: '372270835442-9sq10seokge0bs2bmn2641ubb8pifvn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrntv9jlPFvh9v5gujtBJVXG5BdgdtdRY',
    appId: '1:372270835442:web:984e2f1128f7930eed526b',
    messagingSenderId: '372270835442',
    projectId: 'mock-exam-maker-using-ai-9d0f5',
    authDomain: 'mock-exam-maker-using-ai-9d0f5.firebaseapp.com',
    storageBucket: 'mock-exam-maker-using-ai-9d0f5.appspot.com',
    measurementId: 'G-XBL6WG0ZCF',
  );
}
